# Generated by Django 4.1.1 on 2022-09-23 14:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=250, null=True)),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Incidences',
            },
        ),
        migrations.CreateModel(
            name='Parks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogf_id', models.IntegerField()),
                ('admin_zone', models.CharField(max_length=9)),
                ('general_co', models.CharField(max_length=1)),
                ('geometry_u', models.DateField()),
                ('effective_field', models.DateField()),
                ('system_dat', models.DateField()),
                ('objectid', models.IntegerField()),
                ('shapearea', models.IntegerField()),
                ('shapelen', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
