# Generated by Django 4.1.1 on 2022-09-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parks',
            name='general_co',
        ),
    ]
