# Generated by Django 4.1.1 on 2022-09-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_remove_parks_general_co'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parks',
            new_name='Park',
        ),
    ]
